### ISSUE TITLE
Adding "MB(+ACA)(R)" to hemibrain_roi_meshes

### ISSUE THREAD

**Issue by mmc46** [flyconnectome/hemibrainr#11]
MB(+ACA)(R) is one of the superlevel meshes that is not returned by `hemibrain_roi_meshes()`, although it is in `neuprint_ROIs()`.

Could it be added? It would be useful, as it is an easy way to get the whole MB including the accessory calyces.

**Comment by jefferis** [comment]
What happens if you pass it to the new ROI parameter explicitly?

**Comment by mmc46** [comment]
```
> test = hemibrain_roi_meshes("MB(+ACA)(R)")
> plot3d(test)
Error in mapply(plot3d, x, plotengine = plotengine, col = cols, soma = soma,  : 
  zero-length inputs cannot be mixed with those of non-zero length

> class(test)
[1] "neuronlist" "list"  
```

**Comment by jefferis** [comment]
Yes that’s what I suspected. What about if you try to fetch the mesh in neuprintr directly? I wonder if there’s a problem with the name.

**Comment by mmc46** [comment]
```
mb.aca = neuprint_ROI_mesh("MB(+ACA)(R)")
Error: neuPrint error: Key "MB(+ACA)(R)" not found
```

**Comment by jefferis** [comment]
It seems that meshes are not available for the following:

```
> setdiff(neuprint_ROIs(),names(hemibrain.rois))
 [1] "CX"          "hemibrain"   "INP"         "LX(L)"       "LX(R)"       "MB(+ACA)(R)"
 [7] "OL(R)"       "PENP"        "SNP(L)"      "SNP(R)"      "VLNP(R)"     "VMNP"
```

These ROIs are probably only defined at the level of the voxel-wise segmentation. In any case we can't support this for the time being.
