### ISSUE TITLE
hidden methods

### ISSUE THREAD

**Issue by jefferis** [flyconnectome/hemibrainr#2]
@alexanderbates there are many examples of hidden methods in the package right now. These work when you use `devtools::load_all()` while developing the package but they do not work if you load the package normally (`library(hemibrainr)`) because they are not available for dispatch. You need to mark them with `@export` for roxygen2 to make them visible (see e.g. https://roxygen2.r-lib.org/articles/namespace.html)

**Comment by alexanderbates** [comment]
Ah yes, I had gotten confused, thanks

**Comment by jefferis** [comment]
Unfortunately we both fixed this (my fault for not pushing/assigning). I'll merge and push back as there are a couple little things that were missing.
